---
- hosts: all
  sudo: yes
  
  vars:
  
  vars_files:
  - var/vars.yml

  tasks:
  - include: task/system.yml tags=system
  - include: task/development.yml tags=development
  - include: task/browser.yml tags=browser
  - include: task/ide.yml tags=ide
  - include: task/php.yml tags=php
  - include: task/apache.yml tags=apache
  - include: task/virtualization.yml
