---
- hosts: all
  sudo: yes
  
  vars:
  
  vars_files:
  - var/vars.yml

  tasks:
  - include: task/system.yml tags=system
  - include: task/development.yml tags=development
  - include: task/browser.yml tags=browser
  - include: task/ide.yml tags=ide
  - include: task/php.yml tags=php
  - include: task/apache.yml tags=apache
  - include: task/mysql.yml tags=mysql
  - include: task/virtualization.yml tags=virtualization
  - include: task/mysql-workbench.yml tags=mysql-workbench
  - include: task/phpmyadmin.yml tags=phpmyadmin
  - include: task/sqlite3.yml tags=sqlite3
  - include: task/mongo.yml tags=mongo
  - include: task/sshfs.yml tags=sshfs
  - include: task/gimp.yml tags=gimp
  - include: task/calibre.yml tags=calibre
  - include: task/skype.yml tags=skype
  - include: task/android.yml tags=android
  - include: task/node.yml tags=node
#  - include: task/mount-nietzsche.yml tags=mount-nietzsche
  - include: task/hplip.yml tags=hplip
